### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Twig6943** [ram-on/BlissLauncher-No-Default-Widgets#1]
Please make the users able to toggle the web search feature on the launcher.
![Screenshot_20231113-173311_Bliss Launcher (CTP edition)](https://github.com/ram-on/BlissLauncher-No-Default-Widgets/assets/119701717/f570fe72-f4ce-4a46-8624-bf6dc3e69eac)

**Comment by ram-on** [comment]
Hi, I'm no longer maintaining this project.
